FROM itdoginfo/openwrt-sdk-apk:09102025

ARG PODKOP_VERSION
ENV PODKOP_VERSION=${PODKOP_VERSION}

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop /builder/package/feeds/luci/luci-app-podkop

RUN make defconfig && \
    make package/feeds/utilities/podkop/compile -j1 V=s && \
    make package/feeds/luci/luci-app-podkop/compile -j1 V=s
